### ISSUE TITLE
Snippets from files inside mkdocs project

### ISSUE THREAD

**Issue by gaweCodes** [mprivat/mkdocs-snippet-plugin#7]
I can't find a way to reference a md-file inside the same mkdocs project. Is it possible to reference a file inside the same mkdocs project? How?

I would expect something like this:# Welcome to MkDocs
`{{ snippet('pathToFolderThatContainsTheFileInNextParam, 'README.md', '## Installation') }}`

Of corse the path is relative to the bas_path inside the mkdocs.yml:
```YML
plugin
   - snippet:
      base_path: docs/pfad_zum_snippets_folder
```

The last param of the snippet-function above should be option, so that it will import the whole file. Is this already possible?
